/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TopicWithoutVerbVO } from './topicWithoutVerbVO';

export interface TopicVO {
  addons: Array<TopicWithoutVerbVO>;
  approved: boolean;
  description?: string;
  extensions: Array<TopicWithoutVerbVO>;
  fixed: boolean;
  html?: string;
  id?: number;
  keywords: Array<string>;
  previewImg?: string;
  replacements: Array<TopicWithoutVerbVO>;
  simplifications: Array<TopicWithoutVerbVO>;
  title?: string;
}
